edenia/proton-affiliate

- CODE_OF_CONDUCT.md
> docs(code of conduct): Add Code of Conduct

- contracts/affiliate/src/affiliate.cpp
- hapi/src/services/affiliate.service.js
- hapi/src/services/demux/index.js
- hapi/src/services/demux/updaters/affiliate-addref.updater.js
- hapi/src/services/demux/updaters/affiliate-payref.updater.js
- hapi/src/services/demux/updaters/affiliate-rejectref.update.js
- hapi/src/services/demux/updaters/affiliate-verifyacc.updater.js
- hapi/src/services/demux/updaters/affiliate-verifyexp.updater.js
- hapi/src/services/demux/updaters/affiliate-verifykyc.updater.js
- hapi/src/services/demux/updaters/index.js
- hapi/src/services/index.js
- hapi/src/services/referrals.service.js
- hapi/src/utils/eos.util.js
- hasura/metadata/tables.yaml
- hasura/migrations/1623626228919_create_table_public_referrals/down.sql
- hasura/migrations/1623626228919_create_table_public_referrals/up.sql
- hasura/migrations/1623791456828_create_table_public_referral_history/down.sql
- hasura/migrations/1623791456828_create_table_public_referral_history/up.sql
- Resolve #66 
1. make run
2. execute some action (addref, payref, rejectref, verifyacc, verifyexp, verifykyc)
3. check the table `referral_history` to confirm the new data it's there
> Sync database

- webapp/.babelrc
- webapp/Dockerfile
- webapp/package.json
- webapp/src/context/state.context.js
- webapp/src/routes/Admin/AddUserModal.js
- webapp/src/routes/Admin/index.js
- webapp/src/routes/Admin/styles.js
- webapp/src/routes/index.js
- webapp/src/theme/index.js
- webapp/src/utils/affiliate.js
- webapp/src/utils/get-ual-error.js
- webapp/src/utils/index.js
- webapp/yarn.lock
- Resolve #86
1. make run
2. login with admin user
3. click on "+" button
4. type an account
5. click on "add" button 
6. confirm the message
> feat(webapp): implement add user

- .github/workflows/push-dev-environment.yaml
- .github/workflows/push-prod-environment.yaml
set fixed version tag instead of master
> adjust kubernetes deployment library version

- hapi/package.json
- hapi/src/routes/add-referral.route.js
- hapi/src/routes/index.js
- hapi/src/services/affiliate.service.js
- hapi/yarn.lock
- hasura/metadata/actions.graphql
- hasura/metadata/actions.yaml
- webapp/src/gql/affiliate.js
- webapp/src/gql/index.js
- webapp/src/routes/Admin/UsersTable.js
- webapp/src/routes/Admin/index.js
- webapp/src/routes/Admin/styles.js
- webapp/src/routes/Join/index.js
- webapp/src/routes/Join/styles.js
- webapp/src/routes/index.js
- webapp/src/utils/affiliate.js
- Resolve #90
- Resolve #91 
1. make run
2. login with admin
3. check the users table
> list users

- .github/workflows/push-dev-environment.yaml
- .github/workflows/push-prod-environment.yaml
Fixes error in hasura service startup when applying metadada that references the actions base URL
> add hasura actions base url

- .github/workflows/push-dev-environment.yaml
- .github/workflows/push-prod-environment.yaml
set hasura url for prod and dev environment
> Set hasura url env variable

- webapp/src/components/Autocomplete/index.js
- webapp/src/components/Autocomplete/styles.js
- webapp/src/language/en.json
- webapp/src/routes/Affiliate/index.js
- webapp/src/routes/Affiliate/styles.js
- webapp/src/routes/Home/index.js
- webapp/src/routes/Home/styles.js
- webapp/src/routes/Join/index.js
- Resolve Add i18n
- Resolve Move style code
1. first step
2. next step
> Add i18n and move style code

- webapp/src/routes/Affiliate/index.js
- Resolve Validate no user login
1. first step
2. next step
> Validate no user login

- webapp/src/components/Accordion/index.js
- webapp/src/components/FloatingButon/index.js
- webapp/src/components/FloatingButon/indexBackup.js
- webapp/src/components/Header/index.js
- webapp/src/components/Header/styles.js
- webapp/src/components/TableSearch/index.js
- webapp/src/language/en.json
- webapp/src/routes/Admin/index.js
- webapp/src/routes/Admin/styles.js
- webapp/src/routes/index.js
- Resolve Add Admin page
- Resolve Create table sort and pagination
- Resolve Create accordion component
- Resolve Create FAB with menu
- Resolve Add style changes
- Resolve Add secondary header
1. first step
2. next step
> Admin page

- webapp/src/routes/Admin/index.js
> re-order admin page components

- webapp/Dockerfile
- webapp/src/components/RicardianContract/index.js
- webapp/src/routes/Admin/index.js
- webapp/src/routes/Affiliate/index.js
- webapp/src/utils/affiliate.js
- uses explorer URL for ricardian contract page
- fixes spelling mistake in variable name
- adds todo item
> Adjust variable names

- webapp/src/gql/affiliate.js
- webapp/src/language/en.json
- webapp/src/routes/Admin/index.js
- webapp/src/routes/Home/index.js
- Resolve #116 
- Resolve #117 
1. first step
2. next step
> Approve and reject new users

- webapp/src/components/TableSearch/index.js
- webapp/src/routes/Admin/index.js
- Resolve #157 
1. first step
2. next step
> Add button to show timeline history

- .github/workflows/push-prod-environment.yaml
- webapp/makefile
arguments are case sensitve, the react var was not being rendered correctly
> Fix webapp env var case

- webapp/src/components/HistoryModal/index.js
- webapp/src/components/HistoryModal/styles.js
- webapp/src/components/TableSearch/index.js
- webapp/src/gql/affiliate.js
- webapp/src/language/en.json
- webapp/src/routes/Admin/index.js
- webapp/src/routes/Affiliate/index.js
- webapp/src/routes/Home/index.js
- Resolve #149
1. make run
2. navigate to the home
3. click on the new icon
> feat(webapp): replace TX ID for history modal

- .github/workflows/push-dev-environment.yaml
- .github/workflows/push-prod-environment.yaml
- hasura/metadata/databases/default/tables/public_join_request.yaml
- webapp/src/components/TableSearch/index.js
- webapp/src/components/TableSearch/styles.js
- webapp/src/language/en.json
- webapp/src/routes/Join/index.js
> feat(webapp): update env variables

- webapp/src/routes/Admin/index.js
> feat(webapp): remove cache for new join request

- webapp/src/components/TableSearch/index.js
- webapp/src/routes/Admin/index.js
- Resolve #173 
- Resolve #174 
1. first step
2. next step
> Send accounts instead hasura ids

- webapp/src/components/Footer/index.js
- webapp/src/components/Footer/styles.js
- webapp/src/components/Timeline/index.js
- webapp/src/components/Timeline/styles.js
- webapp/src/language/en.json
- webapp/src/routes/Join/index.js
- Resolve #172 
- Resolve #156 
1. first step
2. next step
> Add Footer

- hapi/src/services/hyperion/index.js
> fix(hapi): missing records on hyperion sync process

- webapp/src/components/Timeline/index.js
- webapp/src/language/en.json
- Resolve #177 
1. first step
2. next step
> Add timeline icons

- hapi/src/services/hyperion/index.js
- hapi/src/utils/axios.util.js
- hapi/src/utils/eos.util.js
- webapp/src/gql/affiliate.js
- webapp/src/language/en.json
- webapp/src/routes/Home/index.js
- webapp/src/routes/Home/styles.js
- webapp/src/routes/Join/index.js
- Resolve #158
1. first step
2. next step
> feat: implement search referral

- hapi/src/services/hyperion/index.js
- webapp/src/components/FloatingButton/styles.js
- webapp/src/language/en.json
> fix: missing action button

- webapp/src/language/en.json
- webapp/src/routes/Join/index.js
- webapp/src/routes/Join/styles.js
- webapp/src/routes/index.js
> fix: ui issues after join

- webapp/src/routes/index.js
> fix: useless option

- webapp/src/components/FloatingButton/styles.js
- Resolve #192 
1. first step
2. next step
> Relocate FAB on admin page

- webapp/src/components/Header/index.js
- webapp/src/components/HistoryModal/index.js
- webapp/src/components/HistoryModal/styles.js
- webapp/src/gql/affiliate.js
- webapp/src/utils/use-imperative-query.js
> feat: add empty state for history modal

- webapp/src/components/HistoryModal/index.js
- webapp/src/components/Timeline/index.js
- webapp/src/components/Timeline/styles.js
- webapp/src/theme/palette.js
- Resolve #188 
- Resolve #189 
1. first step
2. next step
> Add color if node require user action

- webapp/src/components/HistoryModal/index.js
- Validate if children is undefined
1. first step
2. next step
> Validate if children is undefined

- webapp/src/components/Header/index.js
- webapp/src/components/Header/styles.js
- webapp/src/components/TableSearch/index.js
- webapp/src/components/TableSearch/styles.js
- webapp/src/routes/Home/index.js
- webapp/src/routes/Home/styles.js
- Resolve #105 
- Add search box component desktop version
1. first step
2. next step
> Home UI fixes

- webapp/src/components/TableSearch/index.js
- webapp/src/gql/affiliate.js
- webapp/src/routes/Admin/index.js
- webapp/src/routes/Affiliate/index.js
- Resolve #153 
- Resolve #190 
- Resolve #167 
- Resolve #169 
- Resolve #176 
- Add logic to filter row when user click check all rows
1. first step
2. next step
> Table fixes

- webapp/public/index.html
- webapp/src/components/Accordion/index.js
- webapp/src/components/Accordion/styles.js
- webapp/src/components/Footer/styles.js
- webapp/src/components/Header/index.js
- webapp/src/components/Header/styles.js
- webapp/src/components/TableSearch/styles.js
- webapp/src/layouts/Dashboard/index.js
- webapp/src/layouts/Dashboard/styles.js
- webapp/src/routes/About/index.js
- webapp/src/routes/About/styles.js
- webapp/src/routes/Admin/index.js
- webapp/src/routes/Affiliate/index.js
- webapp/src/routes/Affiliate/styles.js
- webapp/src/routes/Help/index.js
- webapp/src/routes/Help/styles.js
- webapp/src/routes/Home/index.js
- webapp/src/routes/Home/styles.js
- webapp/src/routes/Join/index.js
- webapp/src/theme/typography.js
- Resolve #199 
- Resolve #200 
1. first step
2. next step
> Desktop UI fix

- webapp/src/components/Header/index.js
- webapp/src/components/Header/styles.js
- webapp/src/components/HistoryModal/styles.js
- webapp/src/routes/Admin/styles.js
- webapp/src/routes/Home/styles.js
- Resolve #202 
1. first step
2. next step
> Desktop modal size

- webapp/src/components/Header/index.js
- webapp/src/language/en.json
- webapp/src/routes/Admin/index.js
- Resolve #207 
- Resolve #212 
- Resolve #219 
1. first step
2. next step
> Refactor message

- webapp/src/components/TableSearch/index.js
- webapp/src/components/TableSearch/styles.js
- Resolve #224 
1. first step
2. next step
> Add table padding right

- .github/workflows/push-prod-environment.yaml
- Resolve #258 
1. first step
2. next step
> Remove slash from explorer URL

- webapp/src/routes/Affiliate/index.js
- Resolve #257 
1. first step
2. next step
> Affiliate join link

- webapp/src/config/main.config.js
> Fix version string format on footer text

- webapp/src/components/Footer/styles.js
- webapp/src/components/SearchForm/styles.js
-Home Padding
1. first step
2. next step
> Padding home

- webapp/src/components/RicardianContract/styles.js
- Resolve #270 
1. first step
2. next step
> Align icon with title

- webapp/src/language/en.json
- webapp/src/routes/About/index.js
> Add about page texts

- webapp/src/routes/Help/index.js
- webapp/src/routes/Help/styles.js
- Resolve #274 
1. first step
2. next step
> Help icons

- .github/workflows/codeql-analysis.yml
> ci(codeql): remove cpp from codeql analysis

- webapp/src/language/en.json
- webapp/src/routes/Admin/RejectPaymentModal.js
- webapp/src/routes/Admin/index.js
- webapp/src/utils/affiliate.js
- Resolve #13 
1. first step
2. next step
> Add memo to reject payment

- webapp/src/components/TableSearch/styles.js
- webapp/src/routes/About/index.js
- webapp/src/routes/About/styles.js
- Resolve #283 
1. first step
2. next step
> Fix font and spacing

- webapp/src/components/Footer/index.js
- webapp/src/components/Footer/styles.js
- webapp/src/routes/Join/index.js
- webapp/src/routes/Join/styles.js
- Resolve #289 
- Resolve #290 
1. first step
2. next step
> Add validation for invitee account name

- hasura/metadata/actions.yaml
- hasura/metadata/databases/default/tables/public_join_request.yaml
- webapp/yarn.lock
- Add the `guest` user role to send_confirmation
> fix(hasura): allow guest role for send_confirmation

- hapi/src/utils/templates/mail.template.js
- webapp/yarn.lock
- Allows Spark's users to see proton affiliate mail without breakout the mail design
1. Accept the join_request pending request
2. Open mail on Spark and check mail image is on top of the mail and footer at the bottom
> fix(hapi): update mail template

- webapp/src/routes/Home/index.js
- webapp/src/utils/affiliate.js
- Resolve #129 
- Correct kyc validation logic
1. try to apply without kyc
2. try to apply with kyc
> fix(webapp): correct the kyc validation logic

- hapi/src/routes/add-join-request.route.js
- hapi/src/routes/index.js
- hapi/src/services/affiliate.service.js
- hapi/src/services/join-request.service.js
- hasura/metadata/actions.graphql
- hasura/metadata/actions.yaml
- hasura/metadata/databases/default/tables/public_join_request.yaml
- webapp/src/gql/affiliate.js
- webapp/src/routes/Home/index.js
- webapp/yarn.lock
- Add backend KYC validation for malicious users that disable the kyc validation in the frontend.
> fix(webapp): add kyc validation in the backend

- webapp/src/language/en.json
- webapp/src/language/es.json
- webapp/src/routes/Admin/index.js
> feat(webapp): add kyc column in new affiliates

- webapp/package.json
- webapp/src/App.js
- webapp/yarn.lock
> feat(webapp): add ga

- webapp/src/App.js
- webapp/src/components/Header/index.js
- Resolve Google Analytics
1. `make run`
> fix(webapp): implement history change

- webapp/src/App.js
- webapp/yarn.lock
> refactor(webapp): update key for google analytics

- webapp/public/index.html
- webapp/src/App.js
- webapp/src/components/Header/index.js
- Resolve ga connection
1. `make run`
> refactor(webapp): implement script into main html

- webapp/src/language/en.json
- webapp/src/language/es.json
- webapp/src/routes/Admin/index.js
- webapp/src/utils/affiliate.js
- webapp/yarn.lock
> feat(webapp): add sort to Referral Payment

- .github/workflows/push-dev-environment.yaml
- .github/workflows/push-prod-environment.yaml
actions/checkout reds #339
1. first step
2. next step
> Fix: workflow push-prod-environment.yaml is using vulnerable action

- webapp/src/components/Loader/index.js
- webapp/src/routes/Admin/index.js
- webapp/src/routes/Admin/styles.js
- Resolve the `Loader` component color
1. `make run`
> style(webapp): update color for Loader

- .github/workflows/push-dev-environment.yaml
- .github/workflows/push-prod-environment.yaml
> revert steebchen/kubectl to v1.1.0

- hasura/metadata/actions.graphql
- hasura/metadata/databases/databases.yaml
- hasura/metadata/databases/default/tables/public_join_request.yaml
- hasura/metadata/databases/default/tables/public_referral.yaml
- hasura/metadata/databases/default/tables/public_referral_history.yaml
- Resolve missing permission
1. `make run`
> fix(hasura): add status permission

- hapi/src/services/join-request.service.js
- webapp/src/language/en.json
- webapp/src/routes/Home/index.js
- Add comments and improve UX
1. `make run`
> fix(hapi): minor control comments

- hapi/src/utils/templates/mail.template.js
- webapp/yarn.lock
> refactor(hapi): update template

- README.md
- contracts/affiliate/include/affiliate.hpp
- contracts/affiliate/src/affiliate.cpp
- contracts/tests/affiliate.test.js
- hapi/package.json
- hapi/src/utils/templates/mail.template.js
- webapp/package.json
- webapp/src/routes/Help/index.js
> Update github repos

- webapp/src/App.js
fix(webapp):update variable webapp
> fix(webapp):update variable webapp

- docker-compose.yaml
- kubernetes/postgres-statefulset.yaml
fix(postgres):Update postgres version
> fix(postgres):Update postgres version
